### ISSUE TITLE
Questions about your loss function

### ISSUE THREAD

**Issue by JerryPW** [HKUST-3DV/DIM-SLAM#10]
Hi!

I notice there is a step to calculate the mean of the loss function in your paper. However, I haven't found it in your code. Is there any changes or just I miss some details? 

<img width="721" alt="image" src="https://github.com/HKUST-3DV/DIM-SLAM/assets/103237744/41d00160-00f6-4c31-ac5a-7220c3a68f04">
<img width="590" alt="image" src="https://github.com/HKUST-3DV/DIM-SLAM/assets/103237744/0e40e05c-5711-48de-aa1f-c653d0368f81">

**Comment by poptree** [comment]
Hi,

You can use mean or sum in the loss term. I didn't observe performance drop between mean or sum.

**Comment by JerryPW** [comment]
> Hi,
> 
> You can use mean or sum in the loss term. I didn't observe a performance drop between the mean or sum.

OK, I'll try to use mean. Thanks for your reply!
