### ISSUE TITLE
Warping loss construction

### ISSUE THREAD

**Issue by shanjiwei** [HKUST-3DV/DIM-SLAM#11]
Hi, I'd like to ask about a detail mentioned in the paper: why is it necessary to assume that the depth of each pixel point in the patch is the same as the depth of the sampling point when constructing patch-based warping loss? Why not get the depth value corresponding to each pixel in the patch directly from the rendered depth map?
![a5ec54dd3abd31f996394551f0f1319](https://github.com/HKUST-3DV/DIM-SLAM/assets/113739732/f17e14c6-3410-4e8c-b17d-408d4cbb76ae)

**Comment by poptree** [comment]
Hi,

Good question.

"get the depth value corresponding to each pixel in the patch directly from the rendered depth map" implies the requirement of rendering more pixels.

Let A be the number of rendered pixels. If we assume the depth of each pixel point in the patch has the same depth value as the center pixel, we only need to render A pixels. If we get the pixel depth value from the rendered depth map, which implies rendering s*s*A pixels. It will make batch size much larger the the previous one.

Another implementation is using projective warping. However, it requires backward twice, which is also slow, as we mentioned in the rebuttal in OpenReview.

**Comment by poptree** [comment]
I have tried this implementation. However, I only found that it is EXTREMELY time-consuming without any performance boost.
