### ISSUE TITLE
Getting scaleless initialization

### ISSUE THREAD

**Issue by drone-teddy** [HKUST-3DV/DIM-SLAM#16]
Hello, thank you for sharing your great work!
I'm interested in using the code for my project, but I don't have two ground truth poses.
I've tried running the code without the ground truth poses (setting all the poses at an identity) but the sfm doesn't work so well.
Is there a way for me initialize without any prior knowledge of the poses? (I'm don't need the absolute scale).

**Comment by poptree** [comment]
HI
could you provide the figure of the pose and the rendered image?

**Comment by drone-teddy** [comment]
Thank you for the prompt response!
I've attached the final keyframe poses and the rendered image
## With GT poses
![1485](https://github.com/HKUST-3DV/DIM-SLAM/assets/150446386/bbb2303d-573e-403a-bb76-c93870af18af)
![keyframe_ape](https://github.com/HKUST-3DV/DIM-SLAM/assets/150446386/e3eca42a-cd12-42fc-a10e-df89acf9df7b)

## Without GT poses
![1485](https://github.com/HKUST-3DV/DIM-SLAM/assets/150446386/97fd7ebf-c826-4b1f-bf2e-168c2ea4fea6)
![keyframe_ape](https://github.com/HKUST-3DV/DIM-SLAM/assets/150446386/62ed35b2-c1a3-4438-ac91-2c8b7e7af5bd)

I've modified the code to use only the first GT pose, and set the second pose to be the first pose too (i.e. assume all the poses are at pose 1)

**Comment by poptree** [comment]
Hi, 

Do you change the fix_num parameter during init? The attached figure results from setting all camera poses to Identity and  fix_num=0 (without scale correction).

It would be best to decrease the lr for the high-resolution grid for the correct visualization since the default lr is so large that it prevents optimizing the high-resolution grid from overfitting.

![keyframe_ape](https://github.com/HKUST-3DV/DIM-SLAM/assets/18095906/750b0411-2f4d-44c0-a8d9-40323de86e80)

**Comment by poptree** [comment]
Hi,

I ran the whole sequence without the first two camera poses. The figure of the middle images are attached, and the depth is up to a scale.

![0221_165](https://github.com/HKUST-3DV/DIM-SLAM/assets/18095906/ea15f65d-487d-45e5-a215-1a061a459454)
![0316_55](https://github.com/HKUST-3DV/DIM-SLAM/assets/18095906/924237ab-2bdb-432d-95aa-ae0afc47372f)

**Comment by drone-teddy** [comment]
Thank you! I was able to get better result (I probably need to tune the parameters more).
For the paper, did you use the first two ground truth poses, or did you assume poses to be at identity? I'm curious to know what the trajectory performance would be, if I were to try and reimplement your work using nice-slam.
![keyframe_ape](https://github.com/HKUST-3DV/DIM-SLAM/assets/150446386/17270838-97fb-417b-b477-7e0663173184)
![1485](https://github.com/HKUST-3DV/DIM-SLAM/assets/150446386/ed9faf51-7900-4191-996e-4e6079ff2546)

**Comment by poptree** [comment]
Hi, as mentioned in the paper, I set the first two camera poses as GT. If you want to set the first two cameras as identity, you should reset/release the feature grid during initiation to avoid overfitting, as I mentioned above. 

I will release a version of the whole system, implemented by Xunzhi Zheng@HKUST, this weekend.

**Comment by poptree** [comment]
Hi,
You can find the system implementation on "system" branch.
