### ISSUE TITLE
about geometry metric

### ISSUE THREAD

**Issue by llianxu** [HKUST-3DV/DIM-SLAM#18]
Hi, I have a new question. In readme, it was mentioned that **the keyframe selection strategy is not implemented yet, that the quality of final mesh is not good as the paper** But I have checked that the current keyframe selection has already used the overlay format, and then determined whether it is a keyframe, which is the Nice Slam method of adding one every five frames. So I would like to ask which part is not specifically implemented here? Because I found that the structural quality was too poor, I used eval econ.py for evaluation, and the gt mesh used the cut mesh provided by Nice SLAM. So I would like to ask what are the results of your geometry metric testing

Thanks

**Comment by llianxu** [comment]
> Hi, I have a new question. In readme, it was mentioned that **the keyframe selection strategy is not implemented yet, that the quality of final mesh is not good as the paper** But I have checked that the current keyframe selection has already used the overlay format, and then determined whether it is a keyframe, which is the Nice Slam method of adding one every five frames. So I would like to ask which part is not specifically implemented here? Because I found that the structural quality was too poor, I used eval econ.py for evaluation, and the gt mesh used the cut mesh provided by Nice SLAM  Thanks

**Comment by poptree** [comment]
Hi,

The strategy of determining whether a frame is a keyframe or not by optical flow distance. The poor quality of the mesh is due to the five frame strategy. You will see the ceiling depth is wrong at frame 1800 of the office. IF the strategy is correct, the global windows should usually select7-10 frames to form a optimization windows with 21 frames, while this version sometime only can selecting 2-5 frames.

**Comment by poptree** [comment]
I think it is because the code of system is copied from NICE-SLAM, which leads to the poor quality. I also think the overlay function of niceslam has some bugs but I didn't find it yet.

**Comment by llianxu** [comment]
Hi，
Thanks for your response.
I have another question is that in nerf.py,  why you Swapped the shape of the x-axis and z-axis like this
```
 grid_shape = list(map(int, (self.xyz_len / grid_len).tolist()))
 grid_shape[0], grid_shape[2] = grid_shape[2], grid_shape[0]
```

**Comment by poptree** [comment]
Hi,

This part follows with NICE-SLAM, which makes the grid_sample work correctly.

You can see the official doc of Pytorch for more details.

**Comment by llianxu** [comment]
I see，thank you very much
