### ISSUE TITLE
How to run with more frames?

### ISSUE THREAD

**Issue by JunyuanDeng** [HKUST-3DV/DIM-SLAM#2]
Thanks for sharing the code!

From my personal test, the default setting is to run for the first 15 frames. And the corresponding code is: [self.init(15)](https://github.com/HKUST-3DV/DIM-SLAM/blob/main/src/dimslam.py#:~:text=(self)%3A-,self.init(15),-for%20i%20in) in the 51 line of file `dimslam.py`. 

How to run more frames? I simply change 15 to 150, but the results are terrible:

![image](https://user-images.githubusercontent.com/62542727/230858837-8db98d7e-b8e4-49d6-bb05-7f8c4b125c00.png)

**Comment by poptree** [comment]
Hi,

[The rebuttal on the openreview](https://openreview.net/forum?id=QUK1ExlbbA&noteId=La34MUiJpEt) is helpful to answer this question. There is still a gap between DIM-SLAM and "nerf without pose" because DIM-SLAM relies on incremental sfm to recover both scenes and pose.

**Comment by JunyuanDeng** [comment]
Thanks for your reply!

Sorry, I'm still quite confused. 
So, is it mean that there has still gaps to run it for a full sequence of 2000 frames without pose input? Then what's the meaning of the tracking results shown in Table 2? 
Another question is whether the mapping results are based on the GT pose or not.

**Comment by JunyuanDeng** [comment]
I check the Table 2 (tracking result), does it means that the tracking process is only valid for datasets like `fr1/desk`, which has slow motion and small change of pose?  And the mapping results on replica datasets is based a GT pose?

**Comment by JunyuanDeng** [comment]
Sorry, it's just an initialization step. Hope to see the full code!

**Comment by poptree** [comment]
>So, is it mean that there has still gaps to run it for a full sequence of 2000 frames without pose input? Then what's the meaning of the tracking results shown in Table 2?

The mapping and tracking results are running on the whole sequence. As we mentioned in the `implementation detail`, the current version only contains the initialization of DIM-SLAM, while it is also the core part of the whole system. Following the `system` section in paper, you could easily extend the current sfm to the whole sequence.  We will also release the code for the whole system.

When we talk about "nerf without pose" and slam, you should note that they are two different tasks. The recent Nope-Nerf is also based on the incremental sfm and it is far from "nerf without pose".



> I check the Table 2 (tracking result), does it means that the tracking process is only valid for datasets like fr1/desk, which has slow motion and small change of pose? And the mapping results on replica datasets are based a GT pose?

We follow the imap and nice-slam to test DIM-SLAM on the same sequence. The mapping results on replica datasets are based the estimated pose.
