### ISSUE TITLE
Demo video

### ISSUE THREAD

**Issue by mix345** [HKUST-3DV/DIM-SLAM#3]
Thank you very much for your work and the code release! The result is pretty cool.

I have a question about the [demo video in the supplementary material](https://openreview.net/forum?id=QUK1ExlbbA).
In the video, an accurate depth map is rendered from the first frame of the sequence (before starting the process). I am confused because such a depth map can be generated after processing multiple frames and optimizing the implicit map via multi-view posed images. Could you tell me the reason?
<img width="1436" alt="screenshot" src="https://user-images.githubusercontent.com/74367380/230890661-0d4c5df4-df1e-4234-80eb-2ce9900aaf83.png">

Thanks!

**Comment by poptree** [comment]
> Thanks for the reply. OK, so does the rendered depth at the beginning of the video show the one after the initialization process? Then it makes sense.

Yes.
