### ISSUE TITLE
Is there any helpers about how to build the dataset or even the conda environment ?

### ISSUE THREAD

**Issue by JerryPW** [HKUST-3DV/DIM-SLAM#7]
It seems the README file provide few information so that people can't easily replicate your work. Could you provide more specific details? Thanks a lot!

**Comment by poptree** [comment]
Hi,

Thank you for your advice. As I mentioned in the README, this is the re-implementation version of DIM-SLAM. I use the NICE-SLAM as the code base to ensure most parts mentioned in our paper can reproduce and work well.

1. I will add more training detail in the README.
2. In the current version, you can install the conda environment of NICE-SLAM to run DIM-SLAM. The datasets and running commands of these two methods are shared.

Again, thank you for your suggestion.
