### ISSUE TITLE
Meanings about your loss in the code?

### ISSUE THREAD

**Issue by Jerrylihao** [HKUST-3DV/DIM-SLAM#8]
I've read the paper with mentioned there are 3 losses in the whole project: render_loss, warping_loss and smooth_loss, but I only found depth_loss, fake_depth_loss, color_loss, patch_loss, forward_reproj_loss in the code. How does these losses in codes relate with losses in essay? 

Moreover, in the experiment part, you mentioned the coefficient of three losses are 0.5, 0.1, 0.01, respectively. How is these reflected in the paper?

Hoping for your reply soon and thanks for your great job！

**Comment by poptree** [comment]
Hi,

depth_loss is only a reference if the depth map is given. fake_depth_loss is a little trick only applied during initialization, and it is not mentioned in the main paper. Color loss is the render loss in the main paper. patch loss and forward_reproj_loss is the warping loss mentioned in the main paper, while the forward reporj loss is the loss when the patch size =1.

**Comment by Jerrylihao** [comment]
> Hi,
> 
> depth_loss is only a reference if the depth map is given. fake_depth_loss is a little trick only applied during initialization, and it is not mentioned in the main paper. Color loss is the render loss in the main paper. Patch loss and forward_reproj_loss are the warping losses mentioned in the main paper, while the forward reporj loss is the loss when the patch size =1.

Thanks for you reply!!! 
What about your coefficient of three losses? I'm not quite sure where is the code represented. 
By the way, Is smooth_loss represented in the code?

**Comment by poptree** [comment]
Hi,

The code is not sensitive to different coefficients. You could find them with `loss+=`.

For the smooth loss, I found it was useless during re-implementation, thus it was not included in this version.
