### ISSUE TITLE
Missing of some files?

### ISSUE THREAD

**Issue by jingwu2121** [HKUST-3DV/DIM-SLAM#9]
Hi, thank you so much for your great work. 

I am working on a project where we need to implement warping loss, so I hope to rerun your code and figure out how you implement this. But it turns out that this file `data/Replica/office0\\traj.txt` is missing and I am not able find it elsewhere as well. Is it possible that you share this file? I would really appreciate this! 😸

**Comment by poptree** [comment]
Hi,
Please refer to the NICE-SLAM code base. As I mentioned in README.md, this version is re-implement based on NICE-SLAM. The data and the data parser are almost shared. You could find the data in NICE-SLAM too.

**Comment by jingwu2121** [comment]
Thank you 👍

**Comment by jingwu2121** [comment]
Hi,

Sorry for bothering.
I checked the NICE-SLAM code base. They don't have `traj.txt` as well. Their base is like this
![image](https://github.com/HKUST-3DV/DIM-SLAM/assets/98714649/ead172c5-f52c-47e5-b9a5-353f4102854a)

I am a bit confused. 

Could you plz share the link to this file in the NICE-SLAM code base?

Thank you very much 😸

**Comment by poptree** [comment]
Hi,
data/Replica/office0/traj.txt is the trajectory file, you should find it in the data.

Go though the `Demo` section of nice slam:

>>>Replica
>>>Download the data as below and the data is saved into the ./Datasets/Replica folder. Note that the Replica data is generated by the authors of iMAP, so please cite iMAP if you use the data.
